spring.application.name=Simple_Media_Host

spring.datasource.url=jdbc:postgresql://localhost:5432/simple_media_host
spring.datasource.username=media_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.security.user.name=sa
spring.security.user.password=sa